name: flutter_test_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  build_runner:
  flutter_gen_runner:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/colors/

  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/inter/Inter-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/inter/Inter-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/inter/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/inter/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/inter/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/inter/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/inter/Inter-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/inter/Inter-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/inter/Inter-BlackItalic.ttf
          weight: 900
          style: italic
    - family: WorkSans
      fonts:
        - asset: lib/assets/fonts/work_sans/WorkSans-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/work_sans/WorkSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/work_sans/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/work_sans/WorkSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/work_sans/WorkSans-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/work_sans/WorkSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/work_sans/WorkSans-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/work_sans/WorkSans-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/work_sans/WorkSans-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/work_sans/WorkSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/work_sans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/work_sans/WorkSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/work_sans/WorkSans-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/work_sans/WorkSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/work_sans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/work_sans/WorkSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/work_sans/WorkSans-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/work_sans/WorkSans-BlackItalic.ttf
          weight: 900
          style: italic

flutter_gen:
  output: lib/assets/gen/
  line_length: 80

  integrations:
    image: true
    flutter_svg: true

  colors:
    inputs:
      - lib/assets/colors/colors.xml
